import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Начинаем заполнение заказного производства...');

  // Заказ 1 - оригинальные данные из zakaz.md
  const order1 = await prisma.customOrder.create({
    data: {
      orderNumber: 'ZAKAZ-001',
      orderName: 'Заказ на мебель №1',
      requiredDate: new Date('2024-12-31'),
      status: 'PRELIMINARY',
      priority: 1,
      customParts: {
        create: [
          {
            partCode: '1.001',
            partName: 'Вертикальная',
            materialName: 'ЛДСП, 16 мм, Бежевый, U200 ST9, Egger',
            materialSku: '1953.0',
            thickness: 16.0,
            thicknessWithEdging: 16.0,
            quantity: 1,
            blankLength: 750,
            blankWidth: 300.0,
            finishedLength: 750,
            finishedWidth: 300.0,
            edgingSkuL1: '1008',
            edgingNameL1: 'ВенТ 0.4/19',
            edgingSkuL2: '1785',
            edgingNameL2: 'ВТ 2/19',
            edgingSkuW1: '1008',
            edgingNameW1: 'ВенТ 0.4/19',
            edgingSkuW2: '1008',
            edgingNameW2: 'ВенТ 0.4/19',
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '1.002',
            partName: 'Вертикальная',
            materialName: 'ЛДСП, 16 мм, Бежевый, U200 ST9, Egger',
            materialSku: '1953.0',
            thickness: 16.0,
            thicknessWithEdging: 16.0,
            quantity: 1,
            blankLength: 750,
            blankWidth: 300.0,
            finishedLength: 750,
            finishedWidth: 300.0,
            edgingSkuL1: '1008',
            edgingNameL1: 'ВенТ 0.4/19',
            edgingSkuL2: '1785',
            edgingNameL2: 'ВТ 2/19',
            edgingSkuW1: '1008',
            edgingNameW1: 'ВенТ 0.4/19',
            edgingSkuW2: '1008',
            edgingNameW2: 'ВенТ 0.4/19',
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '1.003',
            partName: 'Горизонтальная',
            materialName: 'ЛДСП, 16 мм, Бежевый, U200 ST9, Egger',
            materialSku: '1953.0',
            thickness: 16.0,
            thicknessWithEdging: 16.0,
            quantity: 2,
            blankLength: 568,
            blankWidth: 300.0,
            finishedLength: 568,
            finishedWidth: 300.0,
            edgingSkuL1: '1785',
            edgingNameL1: 'ВТ 2/19',
            edgingSkuL2: '1008',
            edgingNameL2: 'ВенТ 0.4/19',
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '1.004',
            partName: 'Фронтальная',
            materialName: 'ХДФ, 3 мм, Белый лак., Kronostar',
            materialSku: '2001.0',
            thickness: 3.0,
            thicknessWithEdging: 3.0,
            quantity: 1,
            blankLength: 750,
            blankWidth: 600.0,
            finishedLength: 750,
            finishedWidth: 600.0,
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '1.005',
            partName: 'Фронтальная',
            materialName: 'ХДФ, 3 мм, Белый лак., Kronostar',
            materialSku: '2001.0',
            thickness: 3.0,
            thicknessWithEdging: 3.0,
            quantity: 1,
            blankLength: 630,
            blankWidth: 480.0,
            finishedLength: 630,
            finishedWidth: 480.0,
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '1.006',
            partName: 'Профиль',
            materialName: 'Профильная 2205 (60х22х2800)',
            materialSku: '3108.0',
            quantity: 2,
            blankLength: 750,
            finishedLength: 750,
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '1.007',
            partName: 'Профиль',
            materialName: 'Профильная 2205 (60х22х2800)',
            materialSku: '3108.0',
            quantity: 2,
            blankLength: 480,
            finishedLength: 480,
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '2.001',
            partName: 'Горизонтальная',
            materialName: 'ЛДСП, 16 мм, Бежевый, U200 ST9, Egger',
            materialSku: '1953.0',
            thickness: 16.0,
            thicknessWithEdging: 16.0,
            quantity: 2,
            blankLength: 768,
            blankWidth: 300.0,
            finishedLength: 768,
            finishedWidth: 300.0,
            edgingSkuL1: '1785',
            edgingNameL1: 'ВТ 2/19',
            edgingSkuL2: '1008',
            edgingNameL2: 'ВенТ 0.4/19',
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '2.002',
            partName: 'Вертикальная',
            materialName: 'ЛДСП, 16 мм, Бежевый, U200 ST9, Egger',
            materialSku: '1953.0',
            thickness: 16.0,
            thicknessWithEdging: 16.0,
            quantity: 2,
            blankLength: 750,
            blankWidth: 300.0,
            finishedLength: 750,
            finishedWidth: 300.0,
            edgingSkuL1: '1008',
            edgingNameL1: 'ВенТ 0.4/19',
            edgingSkuL2: '1785',
            edgingNameL2: 'ВТ 2/19',
            edgingSkuW1: '1008',
            edgingNameW1: 'ВенТ 0.4/19',
            edgingSkuW2: '1008',
            edgingNameW2: 'ВенТ 0.4/19',
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '2.003',
            partName: 'Фронтальная',
            materialName: 'ХДФ, 3 мм, Белый лак., Kronostar',
            materialSku: '2001.0',
            thickness: 3.0,
            thicknessWithEdging: 3.0,
            quantity: 1,
            blankLength: 750,
            blankWidth: 800.0,
            finishedLength: 750,
            finishedWidth: 800.0,
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '3 (склейка).001',
            partName: 'Горизонтальная',
            materialName: 'ЛМДФ, 16мм, 2хстор. Черный',
            materialSku: 'N/A',
            thickness: 16.0,
            thicknessWithEdging: 18.1,
            quantity: 1,
            blankLength: 1500,
            blankWidth: 816.0,
            finishedLength: 1500,
            finishedWidth: 816.0,
            edgingSkuL1: '(Смотри чертеж)',
            edgingNameL1: '(Смотри чертеж)',
            edgingSkuL2: '(Смотри чертеж)',
            edgingNameL2: '(Смотри чертеж)',
            edgingSkuW1: '(Смотри чертеж)',
            edgingNameW1: '(Смотри чертеж)',
            edgingSkuW2: '(Смотри чертеж)',
            edgingNameW2: '(Смотри чертеж)',
            plasticFace: 'Пленка ПВХ Венге',
            plasticFaceSku: '12877.0',
            plasticBack: 'Металл',
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '3 (склейка).002',
            partName: 'Горизонтальная',
            materialName: 'ЛМДФ, 16мм, 2хстор. Черный',
            materialSku: 'N/A',
            thickness: 16.0,
            thicknessWithEdging: 32.0,
            quantity: 1,
            blankLength: 1500,
            blankWidth: 800.0,
            finishedLength: 1500,
            finishedWidth: 800.0,
            edgingSkuL1: '1003',
            edgingNameL1: 'Ч 0.4/19',
            edgingSkuL2: '1003',
            edgingNameL2: 'Ч 0.4/19',
            edgingSkuW1: '1003',
            edgingNameW1: 'Ч 0.4/19',
            plasticBack: 'ЛДСП, 16 мм, Белый базовый, W908 ST2, Egger',
            plasticBackSku: '1992.0',
            routeId: 4,
            status: 'PENDING',
          },
        ],
      },
    },
  });

  console.log(`Создан заказ 1: ${order1.orderNumber}`);

  // Заказ 2 - измененные данные
  const order2 = await prisma.customOrder.create({
    data: {
      orderNumber: 'ZAKAZ-002',
      orderName: 'Заказ на мебель №2',
      requiredDate: new Date('2025-01-15'),
      status: 'PRELIMINARY',
      priority: 2,
      customParts: {
        create: [
          {
            partCode: '1.001',
            partName: 'Вертикальная',
            materialName: 'ЛДСП, 16 мм, Серый, U200 ST9, Egger',
            materialSku: '1954.0',
            thickness: 16.0,
            thicknessWithEdging: 16.0,
            quantity: 2,
            blankLength: 800,
            blankWidth: 350.0,
            finishedLength: 800,
            finishedWidth: 350.0,
            edgingSkuL1: '1008',
            edgingNameL1: 'ВенТ 0.4/19',
            edgingSkuL2: '1785',
            edgingNameL2: 'ВТ 2/19',
            edgingSkuW1: '1008',
            edgingNameW1: 'ВенТ 0.4/19',
            edgingSkuW2: '1008',
            edgingNameW2: 'ВенТ 0.4/19',
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '1.002',
            partName: 'Горизонтальная',
            materialName: 'ЛДСП, 16 мм, Серый, U200 ST9, Egger',
            materialSku: '1954.0',
            thickness: 16.0,
            thicknessWithEdging: 16.0,
            quantity: 3,
            blankLength: 600,
            blankWidth: 350.0,
            finishedLength: 600,
            finishedWidth: 350.0,
            edgingSkuL1: '1785',
            edgingNameL1: 'ВТ 2/19',
            edgingSkuL2: '1008',
            edgingNameL2: 'ВенТ 0.4/19',
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '1.003',
            partName: 'Фронтальная',
            materialName: 'ХДФ, 3 мм, Черный лак., Kronostar',
            materialSku: '2002.0',
            thickness: 3.0,
            thicknessWithEdging: 3.0,
            quantity: 2,
            blankLength: 800,
            blankWidth: 650.0,
            finishedLength: 800,
            finishedWidth: 650.0,
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '1.004',
            partName: 'Профиль',
            materialName: 'Профильная 2205 (60х22х2800)',
            materialSku: '3108.0',
            quantity: 4,
            blankLength: 800,
            finishedLength: 800,
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '2.001',
            partName: 'Горизонтальная',
            materialName: 'ЛДСП, 16 мм, Серый, U200 ST9, Egger',
            materialSku: '1954.0',
            thickness: 16.0,
            thicknessWithEdging: 16.0,
            quantity: 2,
            blankLength: 820,
            blankWidth: 350.0,
            finishedLength: 820,
            finishedWidth: 350.0,
            edgingSkuL1: '1785',
            edgingNameL1: 'ВТ 2/19',
            edgingSkuL2: '1008',
            edgingNameL2: 'ВенТ 0.4/19',
            routeId: 4,
            status: 'PENDING',
          },
        ],
      },
    },
  });

  console.log(`Создан заказ 2: ${order2.orderNumber}`);

  // Заказ 3 - измененные данные
  const order3 = await prisma.customOrder.create({
    data: {
      orderNumber: 'ZAKAZ-003',
      orderName: 'Заказ на мебель №3',
      requiredDate: new Date('2025-01-30'),
      status: 'PRELIMINARY',
      priority: 3,
      customParts: {
        create: [
          {
            partCode: '1.001',
            partName: 'Вертикальная',
            materialName: 'ЛДСП, 16 мм, Белый, U200 ST9, Egger',
            materialSku: '1955.0',
            thickness: 16.0,
            thicknessWithEdging: 16.0,
            quantity: 1,
            blankLength: 700,
            blankWidth: 280.0,
            finishedLength: 700,
            finishedWidth: 280.0,
            edgingSkuL1: '1008',
            edgingNameL1: 'ВенТ 0.4/19',
            edgingSkuL2: '1785',
            edgingNameL2: 'ВТ 2/19',
            edgingSkuW1: '1008',
            edgingNameW1: 'ВенТ 0.4/19',
            edgingSkuW2: '1008',
            edgingNameW2: 'ВенТ 0.4/19',
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '1.002',
            partName: 'Горизонтальная',
            materialName: 'ЛДСП, 16 мм, Белый, U200 ST9, Egger',
            materialSku: '1955.0',
            thickness: 16.0,
            thicknessWithEdging: 16.0,
            quantity: 2,
            blankLength: 550,
            blankWidth: 280.0,
            finishedLength: 550,
            finishedWidth: 280.0,
            edgingSkuL1: '1785',
            edgingNameL1: 'ВТ 2/19',
            edgingSkuL2: '1008',
            edgingNameL2: 'ВенТ 0.4/19',
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '1.003',
            partName: 'Фронтальная',
            materialName: 'ХДФ, 3 мм, Серый лак., Kronostar',
            materialSku: '2003.0',
            thickness: 3.0,
            thicknessWithEdging: 3.0,
            quantity: 1,
            blankLength: 700,
            blankWidth: 550.0,
            finishedLength: 700,
            finishedWidth: 550.0,
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '1.004',
            partName: 'Профиль',
            materialName: 'Профильная 2205 (60х22х2800)',
            materialSku: '3108.0',
            quantity: 3,
            blankLength: 700,
            finishedLength: 700,
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '2.001',
            partName: 'Вертикальная',
            materialName: 'ЛДСП, 16 мм, Белый, U200 ST9, Egger',
            materialSku: '1955.0',
            thickness: 16.0,
            thicknessWithEdging: 16.0,
            quantity: 2,
            blankLength: 700,
            blankWidth: 280.0,
            finishedLength: 700,
            finishedWidth: 280.0,
            edgingSkuL1: '1008',
            edgingNameL1: 'ВенТ 0.4/19',
            edgingSkuL2: '1785',
            edgingNameL2: 'ВТ 2/19',
            edgingSkuW1: '1008',
            edgingNameW1: 'ВенТ 0.4/19',
            edgingSkuW2: '1008',
            edgingNameW2: 'ВенТ 0.4/19',
            routeId: 4,
            status: 'PENDING',
          },
          {
            partCode: '2.002',
            partName: 'Фронтальная',
            materialName: 'ХДФ, 3 мм, Серый лак., Kronostar',
            materialSku: '2003.0',
            thickness: 3.0,
            thicknessWithEdging: 3.0,
            quantity: 1,
            blankLength: 700,
            blankWidth: 750.0,
            finishedLength: 700,
            finishedWidth: 750.0,
            routeId: 4,
            status: 'PENDING',
          },
        ],
      },
    },
  });

  console.log(`Создан заказ 3: ${order3.orderNumber}`);

  console.log('Заполнение завершено!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
